version: "3"

services:

  myapp:
    build: .
      # context: .
      # dockerfile: pythonImage 
    # networks:
    #   - appNetwork
    ports: 
    - 5000:5000  


  mongodb:
    image: mongo:4.2
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGODB_DATABASE: global
    ports:
    - "27017:27017" 
    volumes:
    - data:/data/db 
    - ./init-db.js:/docker-entrypoint-initdb.d/init-db.js
    # networks:
    # - appNetwork
    healthcheck:
      test: ["CMD", "mongo", "--eval","db.runCommand({ping:1}).ok"]
      interval: 10s
      timeout: 5s
      retries: 5 

  nginx:
    container_name: nginx
    image: nginx:alpine-slim
    ports:
    - 80:80

    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf 
    # networks:
    #   - appNetwork
      
# networks:
#   appNetwork:  

volumes:
  data:
    driver: local    
