name: CI/CD

on:
  push:
    branches:
      - master
      - feature/**

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:

    # checkout
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: docker compose up
      run: docker compose up -d 

    #E2E tests
    - name: E2E
      run: | 
        # bash ./E2E.sh


    # git tag
    - name: tagger
      if: github.ref == 'refs/heads/master'
      id: tagger
      env:          
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      run: |
        tag=$(bash ./tagger.sh)
        export TAG=$tag
        echo "::set-env name=TAG::$TAG"
    # login to dockerhub    
    - name: Login to Docker Hub
      if: github.ref == 'refs/heads/master'
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    # publish  to dockerhub    
    - name: publish to Docker Hub
      if: github.ref == 'refs/heads/master'
      run: |
        docker ps
        docker tag volunteer-myapp:latest eyalbran/volunteer:$TAG
        docker push eyalbran/volunteer:$TAG
       
    # push  tags
    - name: Github login
      if: github.ref == 'refs/heads/master'
      uses: actions/checkout@v3
      with: 
        repository: EyalBran/volunteer
        ref: master
        token: ${{ secrets.TOKEN }}
    - name: push tags
      if: github.ref == 'refs/heads/master'
      run: |
# git remote set-url origin https://${{ secrets.TOKEN }}@github.com/EyalBran/volunteer.git
        git push origin $TAG
    
        

