name: CI/CD

on:
  push:
    branches:
      - master
      - feature/**

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:

    # checkout
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: docker compose up
      run: docker compose up -d 

    #E2E tests
    - name: E2E
      run: | 
        bash ./E2E.sh
      # run: |
      #   sleep 5
      #   docker ps -a
        

